# Generated by Django 5.1.5 on 2026-02-16 16:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Colaborador",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TipoItemAvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimensao",
                    models.CharField(
                        choices=[
                            ("Comportamento", "Comportamento"),
                            ("Entregas", "Entregas"),
                            ("Trabalho em equipe", "Trabalho em equipe"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tipo_item_avaliacao_desempenho",
                    models.CharField(max_length=256, verbose_name="Tipo do Item"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Tipo de Item de Avaliação",
                "ordering": ["dimensao", "tipo_item_avaliacao_desempenho"],
            },
        ),
        migrations.CreateModel(
            name="AvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes_competencia",
                    models.DateField(verbose_name="Mês de competência"),
                ),
                (
                    "status_avaliacao",
                    models.CharField(
                        choices=[
                            ("Criada", "Criada"),
                            ("Em elaboração", "Em elaboração"),
                            ("Em avaliação", "Em avaliação"),
                            ("Concluída", "Concluída"),
                        ],
                        default="Criada",
                        max_length=20,
                    ),
                ),
                ("nota", models.FloatField(default=0, editable=False)),
                (
                    "sugestoes_supervisor",
                    models.TextField(
                        blank=True, default="", verbose_name="Sugestões do supervisor"
                    ),
                ),
                (
                    "observacoes_avaliado",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações do avaliado"
                    ),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes_como_avaliado",
                        to="avaliacoes.colaborador",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaliacoes_como_supervisor",
                        to="avaliacoes.colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Desempenho",
                "ordering": ["-mes_competencia", "colaborador"],
            },
        ),
        migrations.CreateModel(
            name="ItemAvaliacaoDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
                (
                    "avaliacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="avaliacoes.avaliacaodesempenho",
                    ),
                ),
                (
                    "tipo_item_avaliacao_desempenho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="avaliacoes.tipoitemavaliacaodesempenho",
                        verbose_name="Tipo do item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Avaliação",
                "ordering": ["tipo_item_avaliacao_desempenho"],
            },
        ),
        migrations.AddConstraint(
            model_name="avaliacaodesempenho",
            constraint=models.UniqueConstraint(
                fields=("colaborador", "mes_competencia"),
                name="unique_colaborador_mes_competencia",
            ),
        ),
    ]
